In [2]:
import numpy

mat1 = numpy.array([[1, 2], [3, 5]])
mat2 = numpy.array([[4, 8], [6, 10]])

print ("Addition of two matrices: ") 
print (numpy.add(mat1,mat2))       #  add()is used to add matrices

print ("Subtraction of two matrices : ") 
print (numpy.subtract(mat1,mat2))  # subtract()is used to subtract matrices

print ("Matrix Division : ")
print (numpy.divide(mat1,mat2))    # divide()is used to divide matrices

print ("Multiplication of two matrices: ")
print (numpy.multiply(mat1,mat2))   #  multiply()is used to multiply matrices

print ("The product of two matrices : ")
print (numpy.dot(mat1,mat2))

print ("square root is : ")
print (numpy.sqrt(mat1))            # Square root

print ("The summation of elements : ")  
print (numpy.sum(mat2))             #Addition of all the elements

print ("The column wise summation  : ")
print (numpy.sum(mat2,axis=0))

print ("The row wise summation: ")
print (numpy.sum(mat2,axis=1))

print ("Matrix transposition : ")
print (mat1.T)                      # using "T" to transpose the matrix

Addition of two matrices: 
[[ 5 10]
 [ 9 15]]
Subtraction of two matrices : 
[[-3 -6]
 [-3 -5]]
Matrix Division : 
[[0.25 0.25]
 [0.5  0.5 ]]
Multiplication of two matrices: 
[[ 4 16]
 [18 50]]
The product of two matrices : 
[[16 28]
 [42 74]]
square root is : 
[[1.         1.41421356]
 [1.73205081 2.23606798]]
The summation of elements : 
28
The column wise summation  : 
[10 18]
The row wise summation: 
[12 16]
Matrix transposition : 
[[1 3]
 [2 5]]
